// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	reservations "groupproject3-airbnb-api/features/reservations"

	mock "github.com/stretchr/testify/mock"
)

// ReservationServiceInterface is an autogenerated mock type for the ReservationServiceInterface type
type ReservationServiceInterface struct {
	mock.Mock
}

// CheckAvailability provides a mock function with given fields: reservationEntity
func (_m *ReservationServiceInterface) CheckAvailability(reservationEntity reservations.ReservationEntity) (bool, error) {
	ret := _m.Called(reservationEntity)

	var r0 bool
	if rf, ok := ret.Get(0).(func(reservations.ReservationEntity) bool); ok {
		r0 = rf(reservationEntity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(reservations.ReservationEntity) error); ok {
		r1 = rf(reservationEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: reservationEntity
func (_m *ReservationServiceInterface) Create(reservationEntity reservations.ReservationEntity) (reservations.ReservationEntity, error) {
	ret := _m.Called(reservationEntity)

	var r0 reservations.ReservationEntity
	if rf, ok := ret.Get(0).(func(reservations.ReservationEntity) reservations.ReservationEntity); ok {
		r0 = rf(reservationEntity)
	} else {
		r0 = ret.Get(0).(reservations.ReservationEntity)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(reservations.ReservationEntity) error); ok {
		r1 = rf(reservationEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRoomAndDateRange provides a mock function with given fields:
func (_m *ReservationServiceInterface) GetByRoomAndDateRange() ([]reservations.ReservationEntity, error) {
	ret := _m.Called()

	var r0 []reservations.ReservationEntity
	if rf, ok := ret.Get(0).(func() []reservations.ReservationEntity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservations.ReservationEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReservationServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewReservationServiceInterface creates a new instance of ReservationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReservationServiceInterface(t mockConstructorTestingTNewReservationServiceInterface) *ReservationServiceInterface {
	mock := &ReservationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
