// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	rooms "groupproject3-airbnb-api/features/rooms"

	mock "github.com/stretchr/testify/mock"
)

// RoomServiceInterface is an autogenerated mock type for the RoomServiceInterface type
type RoomServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: roomEntity
func (_m *RoomServiceInterface) Create(roomEntity rooms.RoomEntity) (rooms.RoomEntity, error) {
	ret := _m.Called(roomEntity)

	var r0 rooms.RoomEntity
	if rf, ok := ret.Get(0).(func(rooms.RoomEntity) rooms.RoomEntity); ok {
		r0 = rf(roomEntity)
	} else {
		r0 = ret.Get(0).(rooms.RoomEntity)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(rooms.RoomEntity) error); ok {
		r1 = rf(roomEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *RoomServiceInterface) Delete(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *RoomServiceInterface) GetAll() ([]rooms.RoomEntity, error) {
	ret := _m.Called()

	var r0 []rooms.RoomEntity
	if rf, ok := ret.Get(0).(func() []rooms.RoomEntity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rooms.RoomEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *RoomServiceInterface) GetById(id uint) (rooms.RoomEntity, error) {
	ret := _m.Called(id)

	var r0 rooms.RoomEntity
	if rf, ok := ret.Get(0).(func(uint) rooms.RoomEntity); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(rooms.RoomEntity)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserId provides a mock function with given fields: id
func (_m *RoomServiceInterface) GetByUserId(id uint) ([]rooms.RoomEntity, error) {
	ret := _m.Called(id)

	var r0 []rooms.RoomEntity
	if rf, ok := ret.Get(0).(func(uint) []rooms.RoomEntity); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rooms.RoomEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: roomEntity, id
func (_m *RoomServiceInterface) Update(roomEntity rooms.RoomEntity, id uint) (rooms.RoomEntity, error) {
	ret := _m.Called(roomEntity, id)

	var r0 rooms.RoomEntity
	if rf, ok := ret.Get(0).(func(rooms.RoomEntity, uint) rooms.RoomEntity); ok {
		r0 = rf(roomEntity, id)
	} else {
		r0 = ret.Get(0).(rooms.RoomEntity)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(rooms.RoomEntity, uint) error); ok {
		r1 = rf(roomEntity, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRoomServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoomServiceInterface creates a new instance of RoomServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoomServiceInterface(t mockConstructorTestingTNewRoomServiceInterface) *RoomServiceInterface {
	mock := &RoomServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
